import pygame
#Settings
SCREEN_WIDTH = 900
SCREEN_HEIGHT = 600

ASTEROID_MIN_RADIUS = 20
ASTEROID_MID_RADIUS = ASTEROID_MIN_RADIUS * 2
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 1.2  # seconds
ASTEROID_MAX_RADIUS = 60 #ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_IMAGE = pygame.image.load('images/asteroids_asteroid.png')

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
SHOT_RADIUS = 5
PLAYER_SHOOT_COOLDOWN = 0.2
PLAYER_IMAGE = pygame.image.load('images/asteroids_game_ship.png')
